### ISSUE TITLE
write(const(void)[] arr); and write(const(void[]) arr);     Not consistent,  should just use string data type. . 

### ISSUE THREAD

**Issue by Joseph-M-Rice** [deviator/serialport#10]
I tried to write, nothing but compile errors with not being able to cast to void.      Made changes to the code to use string type as the input parameter's type, and fixed the return values on the m_write and write methods.  Will fork and submit a pull request shortly with some fixes.

**Comment by josephRice** [comment]
pull request: https://github.com/deviator/serialport/pull/11

**Comment by deviator** [comment]
I'm sure serialport should not use strings as type for write functions. It is a special and rare case when strings are sent. May be not consistent (`const(void)[]` and `const(void[])`), I agree, but no different in use. What are you mean then wrote about compile errors? Array types casts to `void[]`  silently, but strings are not.

**Comment by josephRice** [comment]
> I'm sure serialport should not use strings as type for write functions. It is a special and rare case when strings are sent. May be not consistent (`const(void)[]` and `const(void[])`), I agree, but no different in use. What are you mean then wrote about compile errors? Array types casts to `void[]` silently, but strings are not.

here are the errors I was seeing
type void is inferred from initializer com.write(cast(const(void[]))data), and variables cannot be of type void
type void is inferred from initializer com.write(sendBuffer), and variables cannot be of type void

Where data is a string
and sendBuffer is a ubyte[]

When working with files,  typically you should be using string data type for the files contents,  as the String class in D is a class to represent a dchar[] array.   Where depending on architecture dchar is utf8 or utf16.  but can be implicitly cast to ubyte[].    

using void in D is also kind of frowned on,  as you should be using auto or a specific data type to represent the data.  void can be used is some cases when making the code more compatible with C/C++ code, but normally you would create D specific wrappers to convert  D Types to the wild card "void" data type so you can interface with C/C++ code. Special considerations need to also be made to convert D Types. For example String class in D does not null terminate as it is a array with a fixed length,  but does provide a 'ptr' property to the pointer of the start of the array.  However that won't work with C/C++ code because it is still not null terminated.  So you have to clone your D string and then also convert using std.string.toStringz or manually concat  - myStrz ~= "\0";   

void arrays void[] also are very limited on what types can implicitly be cast to void[].  ubyte[] can be cast to void[]  but there are some issues, as the void[] array should be large enough to hold the same number of array elements.   Depending on the D compiler you may not be able to have dynamic void[] as a input parameter,  and rather should be using void** over void[].   There is also a limited number of types that can implicitly be cast to void[].   since the type is void[], the D compiler depending on which one might get confused.     

While it is true anything can be cast to a void pointer (void*), it takes extra effort as sometimes you cast or pass the .ptr property, sometimes not depending on the D type's object.   Where on the flip side going from void[] to D types is easy as it can be implicitly cast for more types (some to 1 vs 1 to many).  However there is normally side effects, more error prone, and takes more care to write stable code.

for example  void[] ->  String object  can implicitly happen,   however String -> void[]  can not.   As that it is really void[] -> ubyte[] -> string as the compiler knows how to do this.   To go from a string -> void[],  the application developer must first clone and convert to new ubyte[],  then cast to void[].   This is due to the String object having other properties like .ptr,  and those not being able to be stored as a void[]  as only the strings internal data array and .length property can go to a void[].     

Since you mentioned files being written;  ubyte is probably a better data type to use than void,  so ubyte[]   I think would be a better choice than void[].    As a string can be cast to ubyte[],  and all binary data should be stored in a ubyte[] as a good rule of thumb.    As well as ubyte[] being more portable to other languages that don't have void[],  interfacing with JavaScript blob's for an example  (WASM is coming).  

So to save lot's of headache's for down stream application developers now having to know when to use `to!<T>()` over `cast()`, etc... to get the data they just want to write over the wire to a void[].  I'm going to make an additional change to my branch to do the following. 

1. add additional abstract method overloads for read and write to use string data types.
2. modify the original read and write methods to use ubyte[] instead of void[]   
3. update unit tests to cover these changes.

**Comment by deviator** [comment]
> type void is inferred from initializer com.write(cast(const(void[]))data), and variables cannot be of type void

What are you mean? Casting to `void[]` is implicitly from any array, and you can define data as `void[]`.

```d
import std.stdio;
import std.conv : to;

void foo(const(void)[] arr, size_t line=__LINE__) { writefln("foo:%d  %s", line, arr); }
void bar(const(ubyte)[] arr, size_t line=__LINE__) { writefln("bar:%d  %s", line, arr); }

void main()
{
    struct Baz { align(1): short x, y; ubyte id; }
    
    void[] raw = [1,2,3,4];
    short[] shortData = [10, 12, 15];
    const bazData = [Baz(7,8,9), Baz(6,5,4)];
    
    foo([1,2,3]); // literal of number array is int[] by default
    foo("hello");
    foo(raw);
    foo([Baz(1,2,3), Baz(4,5,6)]);
    foo(bazData);
    foo(shortData);
    
    writeln();

    // int[] by default implicitly convert to ubyte[] and get not what mean
    bar([1,2,3]);

    // you can't pass string to bar without casting!
    bar(cast(ubyte[])"hello");

    // void[] casts to ubyte[] only explicitly
    bar(cast(ubyte[])raw);

    // you need double cast for user defined types
    bar(cast(ubyte[])cast(void[])[Baz(1,2,3), Baz(4,5,6)]);
    bar(cast(ubyte[])cast(void[])bazData);

    // you need cast number arrays too
    bar(cast(ubyte[])shortData);
}
```
output:
```
foo:15  [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0]
foo:16  [104, 101, 108, 108, 111]
foo:17  [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0]
foo:18  [1, 0, 2, 0, 3, 4, 0, 5, 0, 6]
foo:19  [7, 0, 8, 0, 9, 6, 0, 5, 0, 4]
foo:20  [10, 0, 12, 0, 15, 0]

bar:24  [1, 2, 3]
bar:25  [104, 101, 108, 108, 111]
bar:26  [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0]
bar:27  [1, 0, 2, 0, 3, 4, 0, 5, 0, 6]
bar:28  [7, 0, 8, 0, 9, 6, 0, 5, 0, 4]
bar:29  [10, 0, 12, 0, 15, 0]
```

> When working with files, typically you should be using string data type for the files contents

Definitely not typically, at 95% cases I use raw bytes (modbus or other binary protocol). Serialport is not a library for writing files to disk, or user io from keyboard, it's library for communicate with other devices or machines with different physically methods (RS-232, RS-485, UART) that represent in OS as com-ports.

> void arrays void[] also are very limited on what types can implicitly be cast to void[]. ubyte[] can be cast to void[] but there are some issues, as the void[] array should be large enough to hold the same number of array elements

Arrays casted to `void[]` will be same size in bytes as original array. `void[]` is a not typed `ubyte[]` array with same size. Why you think about element count rather count of bytes?

> Depending on the D compiler you may not be able to have dynamic void[] as a input parameter

What compilers you mean? I know what dmd and ldc works fine with `void[]` as well.

> for example void[] -> String object can implicitly happen, however String -> void[] can not. As that it is really void[] -> ubyte[] -> string as the compiler knows how to do this. To go from a string -> void[], the application developer must first clone and convert to new ubyte[], then cast to void[]. 

It's wrong. You can't initialize `string` from `void[]` without casting, but `void[]` variable from `string` you can't initialize because `string` is `immutable(char)[]`. Any immutable arrays must be cloned (`.dup` property) before it can be stored to mutable variable.

> Since you mentioned files being written; ubyte is probably a better data type to use than void, so ubyte[] I think would be a better choice than void[].

`void[]` is good chose for storing unknown typed data. `ubyte[]` is good chose for storing array of `ubyte`. Finally these options are equals but have different syntax. Using `ubyte[]` need more boilerplate code (casting).

> As a string can be cast to ubyte[], and all binary data should be stored in a ubyte[] as a good rule of thumb. As well as ubyte[] being more portable to other languages that don't have void[], interfacing with JavaScript blob's for an example (WASM is coming).

Think of `ubyte[]` and `void[]` as same types. No different under the hood (elements sizes).

I think if you need interface with `string` types you need write wrapper, not pull request.

**Comment by josephRice** [comment]
Ok????    So let's just close an issue because someone raises an issue because they are getting compiler errors from using your library.    I supplied the compiler errors that came back, and outlined the issues with using void in D code.   

Then when someone tries to help the project by submitting code to allow using strings to write data,  the response is because of files.    Which then was pointed out, that ubyte arrays are best practice for binary files.  as well as the problems with converting from D types to other types can't be implicitly done directly to void.   

which got the response `ubyte[]` and `void[]` are the same.    This is not true.     As well as the assertion that in order to use your library you have to create wrappers to use it.   This makes your library not very useful.

As it is natural when using `write(...)`  to want to write a string of text to a file,  or a `ubyte[]`  to write binary data to a file.        

Sorry I tried to help make this code better.     I guess the RED FLAG I had when your project has only read data examples in a 'monitor'  example,  and provided no write examples that this library does not really work and should have continued to look for another library.  

I guess I'll just continue to work my fork of this project and make the improvements that seem to natural, and be more welcoming to anyone that raises issues and are willing to help make it better.

**Comment by deviator** [comment]
> Ok???? So let's just close an issue because someone raises an issue because they are getting compiler errors from using your library. I supplied the compiler errors that came back, and outlined the issues with using void in D code.

I close issue because you suggest that I break my code for reasons that are completely unclear to me. You don't show your code, that not compiles, you don't get info about compiler version, OS.

I don't understand where you get errors at compilation. I wrote this library for my main work and I use it in company projects, and it's works perfect.

> As it is natural when using write(...) to want to write a string of text to a file, or a ubyte[] to write binary data to a file.

Example from https://github.com/deviator/serialport/blob/master/source/serialport/ut.d#L317:
```d
    string msg = sets.front.mode;
    com.write(msg);
```
You can directly use `string` for sending data! Where is problem?

May be you try use library wrong? May be I must wrote more examples? May be you should request more detailed documentation before trying to rewrite code?

In any case the dialogue went wrong. I'm sorry if I offended you somehow, but I really don't understand your problem with my code.
